# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  data-collector:
    storage:
      influxdb:
        host: '%env(DATACOLLECTOR_STORAGE_INFLUX_DB_HOST)%'
        port: '%env(DATACOLLECTOR_STORAGE_INFLUX_DB_PORT)%'
        user: '%env(DATACOLLECTOR_STORAGE_INFLUX_DB_USER)%'
        password: '%env(DATACOLLECTOR_STORAGE_INFLUX_DB_PASSWORD)%'
        use-ssl: '%env(DATACOLLECTOR_STORAGE_INFLUX_DB_USESSL)%'
    doctrine_manager: default

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  DWenzel\DataCollector\:
    resource: '../src/*'
    exclude: ['../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}', '../src/Command/AbstractCommand.php']

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  DWenzel\DataCollector\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  DWenzel\DataCollector\Command\Scheduler\AddCommand:
    arguments:
      - '@doctrine'
      - default
      - '%kernel.logs_dir%'
      #- '%data-collector.doctrine_manager%'
      #- '%data-collector.log_path%'
    tags: [console.command]
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
